baseURL = "https://castelanjr.github.io"
languageCode = "en-us"
title = "Angelo Castelan"

[params]
  name = "Angelo Castelan"
  about = "Android dev @ We Heart It"
  copyright = "Untitled"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = ""
  favicon = "favicon.ico"

    [params.personal]
      name = "Angelo Castelan"
      avatar = "avatar.jpg"
      position = "Android dev @ We Heart It"
      _biography = "I enjoy coding and playing JRPGs, usually not at the same time"

[[params.social]]
  medium = "Twitter"
  icon = "fa-twitter"
  link = "https://twitter.com/castelanjr"

  [[params.social]]
  medium = "Github"
  icon = "fa-github"
  link = "https://github.com/castelanjr"

[[params.social]]
  title = "Instagram"
  icon = "fa-instagram"
  link = "https://instagram.com/castelanjr"

[[params.social]]
  medium = "Facebook"
  icon = "fa-facebook"
  link = "https://www.facebook.com/castelanjr"

[[params.social]]
  medium = "Email"
  icon = "fa-envelope-o"
  link = "mailto:angelo.castelanjr@gmail.com"
